data:
        rachel: true
        in_dim: 259
        d: 30
        batch_size: 32
        tokenizer: 'biomed'
        datajson: 'fake_data/datajson.json' # the datajson file storing details of each study and sequence
        datarootdir: 'fake_data/data' # root dir of where the data is stored
        vqvaename: 'FAKE_TOKENIZER' # name of the VQ-VAE
        percentage: 5
model:
        feature_dim: 128
        visual:
                depth: 8
                heads: 16
                mlp_dim: 1024
                dim_head: 64
                num_classes: 1024
                clsnum: 10
train:
        optimizer: 'adam'
        learning_rate: 0.000002
        weight_decay: 0.0005
        devices: [0]
        epochs: 1000
        ckptsavedir: serieclip_ckpts
        series_dropout_rate: 0.08
        split_finding_rate: 1.0
        warmup: 200
        num_train_loader_workers: 5
        num_val_loader_workers: 1
        token_dropout: 0.03
        init_temperature: 0.07

